Module1 task2
htmlacademy-animation/337099-magic-vacation-1 pull request #2
Opened 2021-03-09 19:27 UTC by emyagkikh

2021-03-11 21:35 UTC, dean992008 requested changes
По самому заданию все сделано правильно, нужно только немного поправить код,

2021-03-11 21:35 UTC, dean992008 commented on source/js/modules/body.js
> +  const setBodyLoadedClassName = () => {
Функцию лучше назвать `onLoadPage` и `pageLoadHandler` чтобы из названия было понятно что это обработчик события. 
Также конкретно здесь в 6 строке можно применить анонимную функцию так как setBodyLoadedClassName не переиспользуется и врядли будет.

2021-03-11 21:35 UTC, dean992008 commented on source/scss/blocks/page-header.scss
> +  & .page-header__logo {
Здесь `&` не нужен. Если его удалить результат будет тот же.  Если идет `&` и после него пробел можно смело удалять. Подобное встречается несколько раз.

2021-03-11 21:35 UTC, dean992008 commented on source/scss/blocks/page-header.scss
> +    transform $window-load-header-logo-transition-duration cubic-bezier(.44,.91,.45,.91) $window-load-header-logo-transition-delay,
Хранить время для анимации в переменых не очень хорошо, так как коефециент переиспользования будет очень низкий (не получится использовать больше 1 или 2 раз), а вот чтение кода оно усложняет и увеличивает размер строки. Поэтому порекомендую использовать значения прямо здесь. 

P.S. Критерия который это требовал бы, насколько я помню, тоже нет.

2021-03-13 07:07 UTC, emyagkikh commented on source/js/modules/body.js
> +  const setBodyLoadedClassName = () => {
Done

2021-03-13 07:07 UTC, emyagkikh commented on source/scss/blocks/page-header.scss
> +  & .page-header__logo {
Done

2021-03-13 07:08 UTC, emyagkikh commented
Исправил обозначенные замечания. В последнем из новых коммитов сделал автофикс стайллинтером, а то ордер в стилях был совсем в хаосе.

2021-03-16 16:44 UTC, merged